In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.7.1+cu118
True


## Introduction To  Tensors

### Creating Tensors

In [2]:
# scalar
scaler = torch.tensor(7)
print(scaler)

tensor(7)


In [3]:
scaler.ndim

0

In [4]:
scaler.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
print(matrix)

tensor([[ 7,  8],
        [ 9, 10]])


In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
# Create a tensor
tensor = torch.tensor([[[1, 2, 3],
                        [7, 8, 9]],
                       
                       [[19, 20, 21],
                        [25, 26, 27]]])
print(tensor)

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[19, 20, 21],
         [25, 26, 27]]])


In [12]:
tensor[0,0:3:2,0:2]

tensor([[1, 2]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([2, 2, 3])

### Random Tensors

In [15]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(2, 4, 4)
random_tensor

tensor([[[0.0335, 0.2718, 0.1997, 0.0909],
         [0.1880, 0.3345, 0.8634, 0.8227],
         [0.4807, 0.1920, 0.3988, 0.9971],
         [0.5237, 0.5643, 0.3411, 0.0053]],

        [[0.9644, 0.3670, 0.0524, 0.9541],
         [0.4409, 0.6381, 0.7086, 0.3005],
         [0.5768, 0.5220, 0.2000, 0.2652],
         [0.2458, 0.3127, 0.2965, 0.1832]]])

In [16]:
random_tensor.ndim

3

In [17]:
# Create a random tensor with similar shape to image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # heght, width, color channels (R, G, B)
print(random_image_tensor.shape, random_image_tensor.ndim)

torch.Size([224, 224, 3]) 3


### Zeros and Ones

In [18]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [32]:
# using torch.arange()
arr = torch.arange(start=-20, end=50, step=7)
arr

tensor([-20, -13,  -6,   1,   8,  15,  22,  29,  36,  43])

In [29]:
# Creating tensors like
tensor_like = torch.zeros_like(input=arr)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])