In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.7.1+cu118
True


## Introduction To  Tensors

### Creating Tensors

In [2]:
# scalar
scaler = torch.tensor(7)
print(scaler)

tensor(7)


In [3]:
scaler.ndim

0

In [4]:
scaler.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
print(matrix)

tensor([[ 7,  8],
        [ 9, 10]])


In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
# Create a tensor
tensor = torch.tensor([[[1, 2, 3],
                        [7, 8, 9]],
                       
                       [[19, 20, 21],
                        [25, 26, 27]]])
print(tensor)

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[19, 20, 21],
         [25, 26, 27]]])


In [12]:
tensor[0,0:3:2,0:2]

tensor([[1, 2]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([2, 2, 3])

### Random Tensors

In [15]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(2, 4, 4)
random_tensor

tensor([[[0.2356, 0.9291, 0.2438, 0.2235],
         [0.2982, 0.9728, 0.2661, 0.3541],
         [0.7875, 0.8278, 0.9973, 0.2873],
         [0.5660, 0.1553, 0.7880, 0.1938]],

        [[0.3225, 0.6535, 0.8497, 0.1177],
         [0.8992, 0.9757, 0.6816, 0.4211],
         [0.8044, 0.2376, 0.4552, 0.8736],
         [0.6860, 0.4613, 0.4776, 0.0328]]])

In [16]:
random_tensor.ndim

3

In [17]:
# Create a random tensor with similar shape to image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # heght, width, color channels (R, G, B)
print(random_image_tensor.shape, random_image_tensor.ndim)

torch.Size([224, 224, 3]) 3


### Zeros and Ones

In [18]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [20]:
# using torch.arange()
arr = torch.arange(start=-20, end=50, step=7)
arr

tensor([-20, -13,  -6,   1,   8,  15,  22,  29,  36,  43])

In [21]:
# Creating tensors like
tensor_like = torch.zeros_like(input=arr)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [29]:
# float tensor
from torch import float16
float_tensor = torch.tensor([3.0, 4.0, 5.0], 
                            dtype=torch.float32,
                            device=None,
                            requires_grad=False)
float_tensor.dtype

torch.float32

In [ ]:
float_half_tensor = torch.tensor([3.0, 4.5, 5.67], 
                                dtype=torch.half)
# float16 tensor can also be created using torch.half
float_half_tensor.dtype

torch.float16

In [ ]:
(float_tensor * float_half_tensor).dtype
# by default, PyTorch will upcast to the higher precision 
# data type when performing operations on tensors 
# of different data types. In this case, the result of 
# multiplying a float32 tensor with a float16 tensor 
# will be a float32 tensor.

torch.float32

In [ ]:
# integer tensor
int_tensor = torch.tensor([3, 4, 5],
                          dtype=torch.int32)
int_tensor, int_tensor.dtype

# Example of exceeding limit of int16
big_int_tensor = torch.tensor([30000, 40000, 50000], dtype=torch.int16)
print(big_int_tensor) # this throws an error because the values exceed the limit of int16

(tensor([3, 4, 5], dtype=torch.int32), torch.int32)

In [38]:
print(int_tensor * float_half_tensor)
(int_tensor * float_half_tensor).dtype
# when multiplying an integer tensor with a float tensor,
# the result will be a float tensor, as PyTorch will upcast
# the integer tensor to the higher precision float tensor.

tensor([ 9.0000, 18.0000, 28.3594], dtype=torch.float16)


torch.float16