In [2]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.7.1+cu118
True


## Introduction To  Tensors

### Creating Tensors

In [3]:
# scalar
scaler = torch.tensor(7)
print(scaler)

tensor(7)


In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
print(matrix)

tensor([[ 7,  8],
        [ 9, 10]])


In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# Create a tensor
tensor = torch.tensor([[[1, 2, 3],
                        [7, 8, 9]],
                       
                       [[19, 20, 21],
                        [25, 26, 27]]])
print(tensor)

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[19, 20, 21],
         [25, 26, 27]]])


In [13]:
tensor[0,0:3:2,0:2]

tensor([[1, 2]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([2, 2, 3])

### Random Tensors

In [16]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(2, 4, 4)
random_tensor

tensor([[[0.0331, 0.0181, 0.5014, 0.9225],
         [0.5231, 0.1139, 0.5874, 0.6295],
         [0.1686, 0.4178, 0.4852, 0.2250],
         [0.1522, 0.1414, 0.9903, 0.1734]],

        [[0.8157, 0.9197, 0.4616, 0.9086],
         [0.9119, 0.0091, 0.6264, 0.8439],
         [0.6480, 0.6627, 0.3455, 0.8713],
         [0.5281, 0.4568, 0.6666, 0.1621]]])

In [17]:
random_tensor.ndim

3

In [18]:
# Create a random tensor with similar shape to image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # heght, width, color channels (R, G, B)
print(random_image_tensor.shape, random_image_tensor.ndim)

torch.Size([224, 224, 3]) 3


### Zeros and Ones

In [19]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [21]:
# using torch.arange()
arr = torch.arange(start=-20, end=50, step=7)
arr

tensor([-20, -13,  -6,   1,   8,  15,  22,  29,  36,  43])

In [22]:
# Creating tensors like
tensor_like = torch.zeros_like(input=arr)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [23]:
# float tensor
from torch import float16
float_tensor = torch.tensor([3.0, 4.0, 5.0], 
                            dtype=torch.float32,
                            device=None,
                            requires_grad=False)
float_tensor.dtype

torch.float32

In [24]:
float_half_tensor = torch.tensor([3.0, 4.5, 5.67], 
                                dtype=torch.half)
# float16 tensor can also be created using torch.half
float_half_tensor.dtype

torch.float16

In [25]:
(float_tensor * float_half_tensor).dtype
# by default, PyTorch will upcast to the higher precision 
# data type when performing operations on tensors 
# of different data types. In this case, the result of 
# multiplying a float32 tensor with a float16 tensor 
# will be a float32 tensor.

torch.float32

In [ ]:
# integer tensor
int_tensor = torch.tensor([3, 4, 5],
                          dtype=torch.int32)
int_tensor, int_tensor.dtype

# Example of exceeding limit of int16
big_int_tensor = torch.tensor([30000, 40000, 50000], dtype=torch.int16)
print(big_int_tensor) # this throws an error because the values exceed the limit of int16

(tensor([3, 4, 5], dtype=torch.int32), torch.int32)

In [ ]:
print(int_tensor * float_half_tensor)
(int_tensor * float_half_tensor).dtype
# when multiplying an integer tensor with a float tensor,
# the result will be a float tensor, as PyTorch will upcast
# the integer tensor to the higher precision float tensor.

tensor([ 9.0000, 18.0000, 28.3594], dtype=torch.float16)


torch.float16

### Some Common Issues with Tensors
1. Tensors not in right datatype
2. Tensors not in right shape
3. Tensors not on right device

In [27]:
# Creating a random tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0371, 0.9611, 0.3015, 0.0183],
        [0.8168, 0.7803, 0.9413, 0.1484],
        [0.2418, 0.1646, 0.9332, 0.7392]])

In [28]:
# printing basic information about the tensor
print(f"Shape of tensor: {random_tensor.shape}")
print(f"Datatype of tensor: {random_tensor.dtype}")
print(f"Device tensor is on: {random_tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is on: cpu


### Tensor Operations
1. Addition
2. Subtraction
3. Element-wise Multiplication
4. Division
5. Matrix Multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
# Adding a scalar to a vector
tensor + 10 
# This adds 10 to each element in the tensor, 
# demonstrating broadcasting.

tensor([11, 12, 13])

In [31]:
# Multiplying a tensor by a scalar
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor
# The original tensor remains unchanged because 
# PyTorch operations return new tensors by default,
# rather than modifying the original tensor in place.

tensor([1, 2, 3])

In [33]:
tensor = tensor * 10
tensor 
# the original tensor is now updated to the new 
# value after multiplication

tensor([10, 20, 30])

In [38]:
tensor / 10

tensor([1., 2., 3.])

In [40]:
# PyTorch in-built functions for some operations
new_tensor = torch.tensor([1, 2, 3, 4])
print(torch.add(new_tensor, 10)) # adds 10 to each element in new_tensor
print(torch.sub(new_tensor, 10)) # subtracts 10 from each element in new_tensor
print(torch.mul(new_tensor, 10)) # multiplies each element in new_tensor by 10
print(torch.div(new_tensor, 10)) # divides each element in new_tensor by 10
print(torch.pow(new_tensor, 2)) # raises each element in new_tensor to the power of 2

tensor([11, 12, 13, 14])
tensor([-9, -8, -7, -6])
tensor([10, 20, 30, 40])
tensor([0.1000, 0.2000, 0.3000, 0.4000])
tensor([ 1,  4,  9, 16])


### Matrix Multiplication
#### Two Main Ways :
1. Element-wise multiplication
2. Matrix Multiplication (Most common in neural networks)

In [43]:
# Element-wise multiplication
print(f'{tensor} * {tensor} = {tensor * tensor}')

tensor([10, 20, 30]) * tensor([10, 20, 30]) = tensor([100, 400, 900])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)
# This performs matrix multiplication (also known as dot product) 
# between the tensor and itself
# tensor = [10, 20, 30] 
# dot product = (10*10) + (20*20) + (30*30) = 100 + 400 + 900 = 1400

tensor(1400)

In [47]:
# Matrix multiplication can also be done by using @ operator
tensor @ tensor

tensor(1400)

In [48]:
# Shape compatibility issues in matrix multiplication
tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_b = torch.tensor([[7, 8],
                         [9, 10], 
                         [11, 12]])

print(torch.matmul(tensor_a, tensor_b))
# This will throw an error because the inner dimensions of 
# the tensors do not match for matrix multiplication.

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
# We can solve this by transposing one of the tensors
# Transposing tensor_b 
tensor_b.T
print(f'Original tensor B shape   = {tensor_b.shape}')
print(f'Transposed tensor B shape = {tensor_b.T.shape}')
print(f"Tensor A shape            = {tensor_a.shape}")

Original tensor B shape   = torch.Size([3, 2])
Transposed tensor B shape = torch.Size([2, 3])
Tensor A shape            = torch.Size([3, 2])


In [51]:
# Now multiplication will work
torch.matmul(tensor_a, tensor_b.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Tensor Aggregation (min, max, mean)

In [59]:
tensor = torch.arange(1, 100)
print(tensor)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99])


In [60]:
torch.min(tensor), torch.max(tensor)

(tensor(1), tensor(99))

In [62]:
torch.mean(tensor.type(torch.float32))

tensor(50.)

In [63]:
torch.sum(tensor)

tensor(4950)

### Finding positions of minimum and maximum elements

In [65]:
torch.argmax(tensor), torch.argmin(tensor)

(tensor(98), tensor(0))

### Reshaping, stacking, suqeezing and unsqueezing tensors

In [66]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [77]:
reshaped = x.reshape(1,9)
reshaped, reshaped.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [78]:
z = x.view(1, 9)
z.shape

torch.Size([1, 9])

In [79]:
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [80]:
# Stacking tensors
stacked = torch.stack([x, x, x], dim=0)
stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# squeezing tensors
squeezed = torch.squeeze(reshaped)
# squeezing removes dimensions of size 1 from the tensor, 
# so the shape of the squeezed tensor will be (9,) instead of (1, 9)
print(f"Original Shape & Size : {reshaped}, {reshaped.shape}\nSqueezed Shape & Size : {squeezed}, {squeezed.shape}")

Original Shape & Size : tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9])
Squeezed Shape & Size : tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9])


In [95]:
# Unsqueezing tensors
unsqueezed = torch.unsqueeze(squeezed, dim=0)
print(f"Original Shape & Size   : {squeezed}, {squeezed.shape}\nUnsqueezed Shape & Size : {unsqueezed}, {unsqueezed.shape}")

Original Shape & Size   : tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9])
Unsqueezed Shape & Size : tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9])


In [ ]:
original = torch.rand(size=(224, 224, 3))
print("Original Shape : ", original.shape)
print("First element before permuting : ", original[0, 0, 0])

# Permuting tensors
permuted = original.permute(2, 0, 1)
print("First element after permuting : ", permuted[0, 0, 0])
print("Permuted Shape : ", permuted.shape)

Original Shape :  torch.Size([224, 224, 3])
Permuted Shape :  torch.Size([3, 224, 224])


### Indexing of tensors

In [98]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [99]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [101]:
x[0,0,0]

tensor(1)

In [102]:
x[:,:,1]

tensor([[2, 5, 8]])